[2022-09-12 04:07:26,428] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T04:07:16.589826+00:00 [queued]>
[2022-09-12 04:07:26,439] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T04:07:16.589826+00:00 [queued]>
[2022-09-12 04:07:26,440] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 04:07:26,441] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-12 04:07:26,442] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 04:07:26,456] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): add-db-data> on 2022-09-12 04:07:16.589826+00:00
[2022-09-12 04:07:26,462] {standard_task_runner.py:52} INFO - Started process 21346 to run task
[2022-09-12 04:07:26,466] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'add-db-data', 'manual__2022-09-12T04:07:16.589826+00:00', '--job-id', '663', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/tcc_dag-checkpoint.py', '--cfg-path', '/tmp/tmpjg_owdym', '--error-file', '/tmp/tmpy9h5deyy']
[2022-09-12 04:07:26,468] {standard_task_runner.py:80} INFO - Job 663: Subtask add-db-data
[2022-09-12 04:07:26,556] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T04:07:16.589826+00:00 [running]> on host b6ddae3e9f9e
[2022-09-12 04:07:26,641] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=add-db-data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T04:07:16.589826+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-12T04:07:16.589826+00:00
[2022-09-12 04:07:26,666] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-12 04:07:26,693] {logging_mixin.py:115} INFO - Database connection closed.
[2022-09-12 04:07:26,707] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-12 04:07:26,737] {logging_mixin.py:115} INFO - Database connection closed.
[2022-09-12 04:07:26,739] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 139, in add_db_data
    df_diff1_tmp.to_csv('./dags/tmp.csv')
AttributeError: 'NoneType' object has no attribute 'to_csv'
[2022-09-12 04:07:26,752] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=add-db-data, execution_date=20220912T040716, start_date=20220912T040726, end_date=20220912T040726
[2022-09-12 04:07:26,764] {standard_task_runner.py:97} ERROR - Failed to execute job 663 for task add-db-data ('NoneType' object has no attribute 'to_csv'; 21346)
[2022-09-12 04:07:26,802] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12 04:07:26,849] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
