[2022-09-09 01:36:50,529] {processor.py:153} INFO - Started process (PID=51) to work on /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:36:50,531] {processor.py:641} INFO - Processing file /opt/airflow/dags/snyk-extract-data.py for tasks to queue
[2022-09-09 01:36:50,532] {logging_mixin.py:115} INFO - [2022-09-09 01:36:50,532] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:36:51,153] {logging_mixin.py:115} INFO - [2022-09-09 01:36:51,151] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/snyk-extract-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snyk-extract-data.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:36:51,155] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:36:51,185] {processor.py:161} INFO - Processing /opt/airflow/dags/snyk-extract-data.py took 0.660 seconds
[2022-09-09 01:37:21,817] {processor.py:153} INFO - Started process (PID=126) to work on /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:37:21,819] {processor.py:641} INFO - Processing file /opt/airflow/dags/snyk-extract-data.py for tasks to queue
[2022-09-09 01:37:21,820] {logging_mixin.py:115} INFO - [2022-09-09 01:37:21,820] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:37:22,258] {logging_mixin.py:115} INFO - [2022-09-09 01:37:22,254] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/snyk-extract-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snyk-extract-data.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:37:22,259] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:37:22,287] {processor.py:161} INFO - Processing /opt/airflow/dags/snyk-extract-data.py took 0.475 seconds
[2022-09-09 01:37:52,528] {processor.py:153} INFO - Started process (PID=207) to work on /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:37:52,530] {processor.py:641} INFO - Processing file /opt/airflow/dags/snyk-extract-data.py for tasks to queue
[2022-09-09 01:37:52,531] {logging_mixin.py:115} INFO - [2022-09-09 01:37:52,531] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:37:52,930] {logging_mixin.py:115} INFO - [2022-09-09 01:37:52,927] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/snyk-extract-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snyk-extract-data.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:37:52,931] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:37:52,949] {processor.py:161} INFO - Processing /opt/airflow/dags/snyk-extract-data.py took 0.426 seconds
[2022-09-09 01:39:03,736] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:39:03,739] {processor.py:641} INFO - Processing file /opt/airflow/dags/snyk-extract-data.py for tasks to queue
[2022-09-09 01:39:03,741] {logging_mixin.py:115} INFO - [2022-09-09 01:39:03,741] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:39:04,881] {logging_mixin.py:115} INFO - [2022-09-09 01:39:04,866] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/snyk-extract-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snyk-extract-data.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:39:04,885] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:39:04,918] {processor.py:161} INFO - Processing /opt/airflow/dags/snyk-extract-data.py took 1.185 seconds
[2022-09-09 01:39:35,101] {processor.py:153} INFO - Started process (PID=117) to work on /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:39:35,102] {processor.py:641} INFO - Processing file /opt/airflow/dags/snyk-extract-data.py for tasks to queue
[2022-09-09 01:39:35,103] {logging_mixin.py:115} INFO - [2022-09-09 01:39:35,103] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:39:35,475] {logging_mixin.py:115} INFO - [2022-09-09 01:39:35,472] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/snyk-extract-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snyk-extract-data.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:39:35,476] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:39:35,500] {processor.py:161} INFO - Processing /opt/airflow/dags/snyk-extract-data.py took 0.404 seconds
[2022-09-09 01:40:05,657] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:40:05,659] {processor.py:641} INFO - Processing file /opt/airflow/dags/snyk-extract-data.py for tasks to queue
[2022-09-09 01:40:05,660] {logging_mixin.py:115} INFO - [2022-09-09 01:40:05,660] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:40:06,289] {logging_mixin.py:115} INFO - [2022-09-09 01:40:06,282] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/snyk-extract-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snyk-extract-data.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:40:06,293] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:40:06,324] {processor.py:161} INFO - Processing /opt/airflow/dags/snyk-extract-data.py took 0.671 seconds
[2022-09-09 01:40:36,417] {processor.py:153} INFO - Started process (PID=272) to work on /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:40:36,418] {processor.py:641} INFO - Processing file /opt/airflow/dags/snyk-extract-data.py for tasks to queue
[2022-09-09 01:40:36,420] {logging_mixin.py:115} INFO - [2022-09-09 01:40:36,420] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:40:36,803] {logging_mixin.py:115} INFO - [2022-09-09 01:40:36,800] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/snyk-extract-data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snyk-extract-data.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:40:36,805] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/snyk-extract-data.py
[2022-09-09 01:40:36,827] {processor.py:161} INFO - Processing /opt/airflow/dags/snyk-extract-data.py took 0.414 seconds
