[2022-09-11 21:44:43,155] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-11T21:44:34.284628+00:00 [queued]>
[2022-09-11 21:44:43,167] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-11T21:44:34.284628+00:00 [queued]>
[2022-09-11 21:44:43,168] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:44:43,169] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-11 21:44:43,170] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:44:43,187] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate-card-trello> on 2022-09-11 21:44:34.284628+00:00
[2022-09-11 21:44:43,194] {standard_task_runner.py:52} INFO - Started process 3926 to run task
[2022-09-11 21:44:43,198] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'generate-card-trello', 'manual__2022-09-11T21:44:34.284628+00:00', '--job-id', '576', '--raw', '--subdir', 'DAGS_FOLDER/tcc_dag.py', '--cfg-path', '/tmp/tmpbun9xiy6', '--error-file', '/tmp/tmp3drcebwk']
[2022-09-11 21:44:43,199] {standard_task_runner.py:80} INFO - Job 576: Subtask generate-card-trello
[2022-09-11 21:44:43,273] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-11T21:44:34.284628+00:00 [running]> on host b6ddae3e9f9e
[2022-09-11 21:44:43,359] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=generate-card-trello
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T21:44:34.284628+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-11T21:44:34.284628+00:00
[2022-09-11 21:44:43,378] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:44:43,381] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:44:43,391] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:44:43,393] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:44:43,394] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tcc_dag.py", line 183, in generate_card_trello
    if len(df1) >0:
TypeError: object of type 'NoneType' has no len()
[2022-09-11 21:44:43,407] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=generate-card-trello, execution_date=20220911T214434, start_date=20220911T214443, end_date=20220911T214443
[2022-09-11 21:44:43,421] {standard_task_runner.py:97} ERROR - Failed to execute job 576 for task generate-card-trello (object of type 'NoneType' has no len(); 3926)
[2022-09-11 21:44:43,454] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-11 21:44:43,492] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
